export const FETCH_QUZES_START = 'FETCH_QUZES_START';
export const FETCH_QUZES_SUCCESS = 'FETCH_QUZES_SUCCESS';
export const FETCH_QUZES_ERROR = 'FETCH_QUZES_ERROR';
export const FETCH_QUIZ_SUCCES = 'FETCH_QUIZ_SUCCES';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATOR = 'RESET_QUIZ_CREATOR';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';